version: '3'
services:
  # MongoDB
  mongodb:
    image: "mongo:6.0.14"
    networks:
      - graylog
    volumes:
      - mongo_data:/data/db

  # OpenSearch
  opensearch:
    image: "opensearchproject/opensearch:2.12.0"
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - action.auto_create_index=false
      - plugins.security.ssl.http.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Kimura0303!!2024
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/opensearch/data
    networks:
      - graylog
    ports:
      - 9200:9200

  # Graylog
  graylog:
    image: "graylog/graylog:6.0"
    environment:
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_PASSWORD_SECRET=Kimura0303!!2024
      - GRAYLOG_ROOT_PASSWORD_SHA2=d058327bb4b75d8601ddc9b4ac34da6c623f7a6c51f9f57f1e2b44874b6351c7
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --timeout=300 -- /docker-entrypoint.sh"
    volumes:
      - "graylog_journal:/usr/share/graylog/data/journal"
      - "graylog_data:/usr/share/graylog/data/data"
    networks:
      - graylog
    depends_on:
      - mongodb
      - opensearch
    links:
      - opensearch
    ports:
      - 9000:9000    # Graylog web interface and REST API
      - 1514:1514    # Syslog TCP
      - 1514:1514/udp  # Syslog UDP
      - 12201:12201  # GELF TCP
      - 12201:12201/udp  # GELF UDP

# Docker Volumes for persisting data
volumes:
  mongo_data:
  es_data:
  graylog_journal:
  graylog_data:

networks:
  graylog:
    driver: bridge